<?php

/**
 * Fixes the broken PHP namespaces generated by Kaitai.
 */
$dir = __DIR__.'/../dist';
$dh = opendir($dir);
while (($f = readdir($dh)) !== false) {
    if (strpos($f, '.php') === false) {
        continue;
    }

    $path = "$dir/$f";
    $data = file_get_contents($path);

    $className = substr($f, 0, -4);

    $data = preg_replace(
        [
            // Remove namespaces that end with the filename because those are
            // only created after the first class which is invalid code.
            "#namespace\ [\\\\a-zA-Z0-9]+$className\;\s+#",
            // Fix references to types that would have been in those namespaces
            "#[\\\\a-zA-Z0-9]+$className\\\\([a-zA-Z0-9]+)#",
        ],
        [
            '',
            '$1',
        ],
        $data
    );

    file_put_contents($path, $data);
}
