<?php

/**
 * Fixes the broken PHP generated by Kaitai.
 */

$wtgPath = __DIR__ . '/../dist/Wtg.php';
$wtgFile = file_get_contents($wtgPath);

$wtgFile = preg_replace(
    [
        // Insert namespace in the top.
        '#(\s+)(class Wtg)#',
        // Remove namespaces in between classes
        '#namespace \\\\Wtg;(\s+)#',
        // Remove \Wtg\Header namespacing used within the code.
        '#\\\\Wtg\\\\#',
        '#\\\\Wtg#',
    ],
    [
        '$1namespace Wtg;$1$2',
        '',
        '',
        'Wtg',
    ],
    $wtgFile
);

file_put_contents($wtgPath, $wtgFile);