<?php

/**
 * Fixes the broken PHP generated by Kaitai.
 */
$dir = __DIR__.'/../dist';
$dh = opendir($dir);
while (($f = readdir($dh)) !== false) {
    if (strpos($f, '.php') === false) {
        echo "Skipping $f\n";
        continue;
    }
    echo "Rewriting $f\n";

    $path = "$dir/$f";
    $data = file_get_contents($path);

    $className = substr($f, 0, -4);

    $data = preg_replace(
        [
            '#namespace\ \\\\[a-zA-Z0-9]+;\s+#',
            "#\\\\$className\\\\([a-zA-Z0-9]+)#",
            "#\\\\($className)#",
        ],
        [
            '',
            '$1',
            '$1',
        ],
        $data
    );

    file_put_contents($path, $data);
}

// $wtgPath = __DIR__.'/../dist/Wtg.php';
// $wtgFile = file_get_contents($wtgPath);

// $wtgFile = preg_replace(
//     [
//         // Insert namespace in the top.
//         '#(\s+)(class Wtg)#',
//         // Remove namespaces in between classes
//         '#namespace \\\\Wtg;(\s+)#',
//         // Remove \Wtg\Header namespacing used within the code.
//         '#\\\\Wtg\\\\#',
//         '#\\\\Wtg#',
//     ],
//     [
//         '$1namespace Wtg;$1$2',
//         '',
//         '',
//         'Wtg',
//     ],
//     $wtgFile
// );

// file_put_contents($wtgPath, $wtgFile);

// $fs = ['EcaParameter', 'FunctionParameter', 'U4Container', 'Error'];
// foreach ($fs as $f) {
//     $path = __DIR__."/../dist/$f.php";
//     $file = file_get_contents($path);
//     $file = preg_replace(
//         [
//             '#namespace\ \\\\'.$f.';\s+#',
//         ],
//         [
//             '',
//         ],
//         $file
//     );
//     file_put_contents($path, $file);
// }
